//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCaNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatVe
    {
        public int MaChiTiet { get; set; }
        public int MaDatVe { get; set; }
        public int MaLichChieu { get; set; }
        public int MaGhe { get; set; }
    
        public virtual DatVe DatVe { get; set; }
        public virtual Ghe Ghe { get; set; }
        public virtual LichChieu LichChieu { get; set; }
    }
}
