//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCaNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatVe
    {
        public DatVe()
        {
            this.ChiTietDatVes = new HashSet<ChiTietDatVe>();
        }
    
        public int MaDatVe { get; set; }
        public int MaNguoiDung { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<ChiTietDatVe> ChiTietDatVes { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
