//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCaNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe
    {
        public Ghe()
        {
            this.ChiTietDatVes = new HashSet<ChiTietDatVe>();
        }
    
        public int MaGhe { get; set; }
        public int MaPhong { get; set; }
        public string Hang { get; set; }
        public int Cot { get; set; }
    
        public virtual ICollection<ChiTietDatVe> ChiTietDatVes { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
    }
}
