//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCaNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        public LichChieu()
        {
            this.ChiTietDatVes = new HashSet<ChiTietDatVe>();
        }
    
        public int MaLichChieu { get; set; }
        public int MaPhim { get; set; }
        public int MaPhong { get; set; }
        public System.DateTime NgayChieu { get; set; }
        public System.TimeSpan GioChieu { get; set; }
        public decimal GiaVe { get; set; }
    
        public virtual ICollection<ChiTietDatVe> ChiTietDatVes { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
    }
}
