//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCaNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        public Phim()
        {
            this.LichChieux = new HashSet<LichChieu>();
        }
    
        public int MaPhim { get; set; }
        public string TenPhim { get; set; }
        public int ThoiLuong { get; set; }
        public string TheLoai { get; set; }
        public string QuocGia { get; set; }
        public Nullable<int> NamSX { get; set; }
        public Nullable<System.DateTime> NgayCongChieu { get; set; }
    
        public virtual ICollection<LichChieu> LichChieux { get; set; }
    }
}
