//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCaNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongChieu
    {
        public PhongChieu()
        {
            this.Ghes = new HashSet<Ghe>();
            this.LichChieux = new HashSet<LichChieu>();
        }
    
        public int MaPhong { get; set; }
        public string TenPhong { get; set; }
    
        public virtual ICollection<Ghe> Ghes { get; set; }
        public virtual ICollection<LichChieu> LichChieux { get; set; }
    }
}
