//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCaNhan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLRapDBEntities1 : DbContext
    {
        public QLRapDBEntities1()
            : base("name=QLRapDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietDatVe> ChiTietDatVes { get; set; }
        public DbSet<DatVe> DatVes { get; set; }
        public DbSet<Ghe> Ghes { get; set; }
        public DbSet<LichChieu> LichChieux { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<Phim> Phims { get; set; }
        public DbSet<PhongChieu> PhongChieux { get; set; }
    }
}
